import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    image: "https://res.cloudinary.com/sameep1/image/upload/v1647955198/project_Ecomm/air2_lsfzfb.jpg",
    title: "NIKE",
    productName: "Jordan 1 UNC Chicago",
    price: 53000,
    brand: "nike",
    size: 4.5,
    categoryName: "non-fiction",
  },
  {
    _id: uuid(),
    image: "https://res.cloudinary.com/sameep1/image/upload/v1647955207/project_Ecomm/product5_qcebfo.jpg",
    title: "NIKE",
    productName: "Jordan 1 Black Toe",
    price: 27000,
    brand: "jordan",
    size: 7,
    categoryName: "horror",
  },
  {
    _id: uuid(),
    image: "https://images.unsplash.com/photo-1610870372593-a8647b04451f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    title: "NIKE",
    productName: "Jordan 1 Retro OG",
    price: 23000,
    brand: "Nikelab",
    size: 9,
    categoryName: "fiction",
  },
  {
    _id: uuid(),
    image: "https://res.cloudinary.com/sameep1/image/upload/v1647955202/project_Ecomm/product4_vr2ao0.jpg",
    title: "NIKE",
    productName: "Jordan 1 Shadow",
    price: 30000,
    brand: "jordan",
    size: 5,
    categoryName: "horror",
  },
  {
    _id: uuid(),
    image: "https://res.cloudinary.com/sameep1/image/upload/v1647955194/project_Ecomm/air1_jifei7.jpg",
    title: "NIKE",
    productName: "Jordan 1 X OFF-WHITE",
    price: 43000,
    brand: "jordan",
    size: 9,
    categoryName: "horror",
  },
  {
    _id: uuid(),
    image: "https://res.cloudinary.com/sameep1/image/upload/v1647955196/project_Ecomm/product2_znlj6f.jpg",
    title: "NIKE",
    productName: "Jordan 1 Powder Blue",
    price: 16000,
    brand: "jordan",
    size: 6,
    categoryName: "horror",
  },
  {
    _id: uuid(),
    image: "https://res.cloudinary.com/sameep1/image/upload/v1647955193/project_Ecomm/product1_omgado.jpg",
    title: "NIKE",
    productName: "Jordan 1 x Travis Scott",
    price: 21000,
    brand: "jordan",
    size: 6,
    categoryName: "horror",
  },
  {
    _id: uuid(),
    image: "https://res.cloudinary.com/sameep1/image/upload/v1647955193/project_Ecomm/product6_ikjb4j.jpg",
    title: "NIKE",
    productName: "Jordan 1 Clean Slate",
    price: 18000,
    brand: "jordan",
    size: 9,
    categoryName: "horror",
  },
  {
    _id: uuid(),
    image: "https://res.cloudinary.com/sameep1/image/upload/v1647955193/project_Ecomm/aforce1_h0lbzs.jpg",
    title: "NIKE",
    productName: "Air Force 1 Colours",
    price: 12000,
    brand: "jordan",
    size: 5,
    categoryName: "horror",
  },
  {
    _id: uuid(),
    image: "https://res.cloudinary.com/sameep1/image/upload/v1647955194/project_Ecomm/aforce2_ope3pt.jpg",
    title: "NIKE",
    productName: "Air Force 1 Gray",
    price: 10000,
    brand: "jordan",
    size: 7,
    categoryName: "horror",
  },
  {
    _id: uuid(),
    image: "https://res.cloudinary.com/sameep1/image/upload/v1647955193/project_Ecomm/product3_samqkp.jpg",
    title: "NIKE",
    productName: "Jordan 5 Purple",
    price: 25000,
    brand: "jordan",
    size: 7,
    categoryName: "horror",
  },
];
